# -*- coding: utf-8 -*-
PROPERTY_VALUES = {
    1: {
        "rank": 1,
        "property_costs": {
            "Ближний бой": {"cost": -0.96, "delta_win_rate": -0.295},
            "Магическое": {"cost": 7.85, "delta_win_rate": 0.495},
            "Бронебойность X": {"cost": 1.35, "delta_win_rate": 0.25},
            "Эскалация X": {"cost": 0.37, "delta_win_rate": 0.08},
            "Перезарядка X": {"cost": -1.46, "delta_win_rate": -0.42},
            "Стабилизация X": {"cost": 1.95, "delta_win_rate": 0.315},
            "Кровотечение X": {"cost": 0.00, "delta_win_rate": 0},
            "Гарант X": {"cost": 0.00, "delta_win_rate": 0},
            "Агрессивный обстрел": {"cost": 1.66, "delta_win_rate": 0.285},
            "Ошеломление X": {"cost": 0.66, "delta_win_rate": 0.14},
            "Замедление": {"cost": 0.00, "delta_win_rate": 0},
            "Опасное X": {"cost": -1.11, "delta_win_rate": -0.34},
            "Риск": {"cost": -0.67, "delta_win_rate": -0.22},
            "Пробивание X": {"cost": 1.95, "delta_win_rate": 0.315},
            "Дезориентирующее": {"cost": 0.00, "delta_win_rate": 0},
            "Обездвиживание X": {"cost": 0.00, "delta_win_rate": 0},
            "Точность X": {"cost": 1.61, "delta_win_rate": 0.28},
            "Досягаемость X": {"cost": 0.00, "delta_win_rate": 0},
        },
    },
    2: {
        "rank": 2,
        "property_costs": {
            "Ближний бой": {"cost": -1.25, "delta_win_rate": -0.23},
            "Магическое": {"cost": 9.27, "delta_win_rate": 0.46},
            "Бронебойность X": {"cost": 0.00, "delta_win_rate": 0},
            "Эскалация X": {"cost": 0.19, "delta_win_rate": 0.025},
            "Перезарядка X": {"cost": -2.43, "delta_win_rate": -0.42},
            "Стабилизация X": {"cost": 1.73, "delta_win_rate": 0.205},
            "Кровотечение X": {"cost": 0.00, "delta_win_rate": 0},
            "Гарант X": {"cost": 0.00, "delta_win_rate": 0},
            "Агрессивный обстрел": {"cost": 2.81, "delta_win_rate": 0.275},
            "Ошеломление X": {"cost": 0.00, "delta_win_rate": 0},
            "Замедление": {"cost": 0.00, "delta_win_rate": 0},
            "Опасное X": {"cost": -1.07, "delta_win_rate": -0.19},
            "Риск": {"cost": -0.97, "delta_win_rate": -0.17},
            "Пробивание X": {"cost": 1.73, "delta_win_rate": 0.205},
            "Дезориентирующее": {"cost": 0.00, "delta_win_rate": 0},
            "Обездвиживание X": {"cost": 0.00, "delta_win_rate": 0},
            "Точность X": {"cost": 1.58, "delta_win_rate": 0.19},
            "Досягаемость X": {"cost": 0.00, "delta_win_rate": 0},
        },
    },
    3: {
        "rank": 3,
        "property_costs": {
            "Ближний бой": {"cost": -2.11, "delta_win_rate": -0.235},
            "Магическое": {"cost": 10.67, "delta_win_rate": 0.45},
            "Бронебойность X": {"cost": 0.00, "delta_win_rate": 0},
            "Эскалация X": {"cost": 0.16, "delta_win_rate": 0.015},
            "Перезарядка X": {"cost": -3.48, "delta_win_rate": -0.395},
            "Стабилизация X": {"cost": 2.14, "delta_win_rate": 0.155},
            "Кровотечение X": {"cost": 0.00, "delta_win_rate": 0},
            "Гарант X": {"cost": 0.00, "delta_win_rate": 0},
            "Агрессивный обстрел": {"cost": 4.44, "delta_win_rate": 0.25},
            "Ошеломление X": {"cost": 0.00, "delta_win_rate": 0},
            "Замедление": {"cost": 0.00, "delta_win_rate": 0},
            "Опасное X": {"cost": -1.24, "delta_win_rate": -0.13},
            "Риск": {"cost": -1.52, "delta_win_rate": -0.165},
            "Пробивание X": {"cost": 2.14, "delta_win_rate": 0.155},
            "Дезориентирующее": {"cost": 0.00, "delta_win_rate": 0},
            "Обездвиживание X": {"cost": 0.00, "delta_win_rate": 0},
            "Точность X": {"cost": 1.91, "delta_win_rate": 0.145},
            "Досягаемость X": {"cost": 0.00, "delta_win_rate": 0},
        },
    },
    4: {
        "rank": 4,
        "property_costs": {
            "Ближний бой": {"cost": 0.00, "delta_win_rate": 0},
            "Магическое": {"cost": 9.00, "delta_win_rate": 0.45},
            "Бронебойность X": {"cost": 0.00, "delta_win_rate": 0},
            "Эскалация X": {"cost": 0.18, "delta_win_rate": 0.01},
            "Перезарядка X": {"cost": -6.49, "delta_win_rate": -0.36},
            "Стабилизация X": {"cost": 1.69, "delta_win_rate": 0.1},
            "Кровотечение X": {"cost": 0.00, "delta_win_rate": 0},
            "Гарант X": {"cost": 0.00, "delta_win_rate": 0},
            "Агрессивный обстрел": {"cost": 9.00, "delta_win_rate": 0.215},
            "Ошеломление X": {"cost": 0.00, "delta_win_rate": 0},
            "Замедление": {"cost": 0.00, "delta_win_rate": 0},
            "Опасное X": {"cost": -2.11, "delta_win_rate": -0.09},
            "Риск": {"cost": -2.89, "delta_win_rate": -0.125},
            "Пробивание X": {"cost": 1.69, "delta_win_rate": 0.1},
            "Дезориентирующее": {"cost": 0.00, "delta_win_rate": 0},
            "Обездвиживание X": {"cost": 0.00, "delta_win_rate": 0},
            "Точность X": {"cost": 1.61, "delta_win_rate": 0.095},
            "Досягаемость X": {"cost": 0.00, "delta_win_rate": 0},
        },
    },
}
