# -*- coding: cp1251 -*-
PROPERTY_VALUES = {
    1: {
        "rank": 1,
        "property_costs": {
            "Огонь на подавление": {"cost": 0.00, "delta_win_rate": 0},
            "Магическое": {"cost": 0.00, "delta_win_rate": 0},
            "Бронебойность Х": {"cost": 0.00, "delta_win_rate": 0},
            "Бесшумное": {"cost": 0.00, "delta_win_rate": 0},
            "Эскалация Х": {"cost": 0.37, "delta_win_rate": 0.08},
            "Сплеш Х": {"cost": 0.00, "delta_win_rate": 0},
            "Перезарядка Х": {"cost": -1.46, "delta_win_rate": -0.42},
            "Стабилизация X": {"cost": 1.95, "delta_win_rate": 0.315},
            "Досягаемость Х": {"cost": 0.76, "delta_win_rate": 0.16},
            "Скрытное Х": {"cost": 0.00, "delta_win_rate": 0},
            "Легкое": {"cost": 0.00, "delta_win_rate": 0},
            "Точность Х": {"cost": 1.61, "delta_win_rate": 0.28},
            "Гарант Х": {"cost": 0.00, "delta_win_rate": 0},
            "Агрессивный обстрел": {"cost": 0.66, "delta_win_rate": 0.14},
            "Ошеломление X": {"cost": 0.66, "delta_win_rate": 0.14},
            "А-фактор": {"cost": 0.00, "delta_win_rate": 0},
            "Замедление": {"cost": 0.00, "delta_win_rate": 0},
            "Опасное Х": {"cost": -1.11, "delta_win_rate": -0.34},
            "Риск": {"cost": -0.67, "delta_win_rate": -0.22},
            "Точное X": {"cost": 0.00, "delta_win_rate": 0},
            "Пробитие X": {"cost": 0.00, "delta_win_rate": 0},
            "Кровотечение Х": {"cost": 0.74, "delta_win_rate": 0.155},
            "Дезориентирующее": {"cost": 0.00, "delta_win_rate": 0},
            "Обездвиживание Х": {"cost": 0.00, "delta_win_rate": 0},
        },
    },
    2: {
        "rank": 2,
        "property_costs": {
            "Огонь на подавление": {"cost": 0.00, "delta_win_rate": 0},
            "Магическое": {"cost": 0.00, "delta_win_rate": 0},
            "Бронебойность Х": {"cost": 0.00, "delta_win_rate": 0},
            "Бесшумное": {"cost": 0.00, "delta_win_rate": 0},
            "Эскалация Х": {"cost": 0.19, "delta_win_rate": 0.025},
            "Сплеш Х": {"cost": 0.00, "delta_win_rate": 0},
            "Перезарядка Х": {"cost": -2.43, "delta_win_rate": -0.42},
            "Стабилизация X": {"cost": 1.73, "delta_win_rate": 0.205},
            "Досягаемость Х": {"cost": 0.00, "delta_win_rate": 0},
            "Скрытное Х": {"cost": 0.00, "delta_win_rate": 0},
            "Легкое": {"cost": 0.00, "delta_win_rate": 0},
            "Точность Х": {"cost": 1.58, "delta_win_rate": 0.19},
            "Гарант Х": {"cost": 0.04, "delta_win_rate": 0.005},
            "Агрессивный обстрел": {"cost": 1.00, "delta_win_rate": 0.13},
            "Ошеломление X": {"cost": 0.00, "delta_win_rate": 0},
            "А-фактор": {"cost": 0.00, "delta_win_rate": 0},
            "Замедление": {"cost": 0.00, "delta_win_rate": 0},
            "Опасное Х": {"cost": -1.11, "delta_win_rate": -0.195},
            "Риск": {"cost": -1.02, "delta_win_rate": -0.175},
            "Точное X": {"cost": 0.00, "delta_win_rate": 0},
            "Пробитие X": {"cost": 0.00, "delta_win_rate": 0},
            "Кровотечение Х": {"cost": 0.65, "delta_win_rate": 0.085},
            "Дезориентирующее": {"cost": 0.00, "delta_win_rate": 0},
            "Обездвиживание Х": {"cost": 0.00, "delta_win_rate": 0},
        },
    },
    3: {
        "rank": 3,
        "property_costs": {
            "Огонь на подавление": {"cost": 0.00, "delta_win_rate": 0},
            "Магическое": {"cost": 0.00, "delta_win_rate": 0},
            "Бронебойность Х": {"cost": 0.00, "delta_win_rate": 0},
            "Бесшумное": {"cost": 0.00, "delta_win_rate": 0},
            "Эскалация Х": {"cost": 0.16, "delta_win_rate": 0.015},
            "Сплеш Х": {"cost": 0.00, "delta_win_rate": 0},
            "Перезарядка Х": {"cost": -3.50, "delta_win_rate": -0.395},
            "Стабилизация X": {"cost": 2.14, "delta_win_rate": 0.155},
            "Досягаемость Х": {"cost": 0.05, "delta_win_rate": 0.005},
            "Скрытное Х": {"cost": 0.00, "delta_win_rate": 0},
            "Легкое": {"cost": 0.00, "delta_win_rate": 0},
            "Точность Х": {"cost": 1.91, "delta_win_rate": 0.145},
            "Гарант Х": {"cost": 0.00, "delta_win_rate": 0},
            "Агрессивный обстрел": {"cost": 1.49, "delta_win_rate": 0.12},
            "Ошеломление X": {"cost": 0.00, "delta_win_rate": 0},
            "А-фактор": {"cost": 0.00, "delta_win_rate": 0},
            "Замедление": {"cost": 0.00, "delta_win_rate": 0},
            "Опасное Х": {"cost": -1.29, "delta_win_rate": -0.135},
            "Риск": {"cost": -1.54, "delta_win_rate": -0.165},
            "Точное X": {"cost": 0.00, "delta_win_rate": 0},
            "Пробитие X": {"cost": 0.00, "delta_win_rate": 0},
            "Кровотечение Х": {"cost": 0.61, "delta_win_rate": 0.055},
            "Дезориентирующее": {"cost": 0.00, "delta_win_rate": 0},
            "Обездвиживание Х": {"cost": 0.00, "delta_win_rate": 0},
        },
    },
    4: {
        "rank": 4,
        "property_costs": {
            "Огонь на подавление": {"cost": 0.00, "delta_win_rate": 0},
            "Магическое": {"cost": 0.00, "delta_win_rate": 0},
            "Бронебойность Х": {"cost": 0.00, "delta_win_rate": 0},
            "Бесшумное": {"cost": 0.00, "delta_win_rate": 0},
            "Эскалация Х": {"cost": 0.09, "delta_win_rate": 0.005},
            "Сплеш Х": {"cost": 0.00, "delta_win_rate": 0},
            "Перезарядка Х": {"cost": -6.49, "delta_win_rate": -0.36},
            "Стабилизация X": {"cost": 1.64, "delta_win_rate": 0.1},
            "Досягаемость Х": {"cost": 0.00, "delta_win_rate": 0},
            "Скрытное Х": {"cost": 0.00, "delta_win_rate": 0},
            "Легкое": {"cost": 0.00, "delta_win_rate": 0},
            "Точность Х": {"cost": 1.49, "delta_win_rate": 0.09},
            "Гарант Х": {"cost": 0.00, "delta_win_rate": 0},
            "Агрессивный обстрел": {"cost": 1.56, "delta_win_rate": 0.095},
            "Ошеломление X": {"cost": 0.00, "delta_win_rate": 0},
            "А-фактор": {"cost": 0.00, "delta_win_rate": 0},
            "Замедление": {"cost": 0.00, "delta_win_rate": 0},
            "Опасное Х": {"cost": -2.11, "delta_win_rate": -0.09},
            "Риск": {"cost": -2.77, "delta_win_rate": -0.12},
            "Точное X": {"cost": 0.00, "delta_win_rate": 0},
            "Пробитие X": {"cost": 0.00, "delta_win_rate": 0},
            "Кровотечение Х": {"cost": 0.45, "delta_win_rate": 0.025},
            "Дезориентирующее": {"cost": 0.00, "delta_win_rate": 0},
            "Обездвиживание Х": {"cost": 0.00, "delta_win_rate": 0},
        },
    },
}
