# -*- coding: utf-8 -*-
PROPERTY_VALUES = {
    1: {
        "rank": 1,
        "property_costs": {
            "melee": {
                "Accuracy 1": {"cost": 1.58, "delta_win_rate": 0.28},
                "Armor Pierce 1": {"cost": 0.87, "delta_win_rate": 0.18},
                "Bleed 1": {"cost": 0.02, "delta_win_rate": 0.005},
                "Dangerous 1": {"cost": -1.12, "delta_win_rate": -0.34},
                "Disorienting 1": {"cost": 0.02, "delta_win_rate": 0.005},
                "Escalation 1": {"cost": 0.37, "delta_win_rate": 0.08},
                "Guarantee 1": {"cost": 0.00, "delta_win_rate": 0},
                "Immobilize 1": {"cost": 0.56, "delta_win_rate": 0.12},
                "Magical 1": {"cost": 7.78, "delta_win_rate": 0.505},
                "Penetration 1": {"cost": 0.00, "delta_win_rate": 0},
                "Reach 1": {"cost": 0.37, "delta_win_rate": 0.08},
                "Risk 1": {"cost": -0.51, "delta_win_rate": -0.175},
                "Slow 1": {"cost": 0.37, "delta_win_rate": 0.08},
                "Stun 1": {"cost": 0.95, "delta_win_rate": 0.195},
            },
            "ranged": {
                "Accuracy 1": {"cost": 1.61, "delta_win_rate": 0.28},
                "Aggressive Fire 1": {"cost": 1.66, "delta_win_rate": 0.285},
                "Armor Pierce 1": {"cost": 1.48, "delta_win_rate": 0.265},
                "Bleed 1": {"cost": 0.00, "delta_win_rate": 0},
                "Dangerous 1": {"cost": -1.12, "delta_win_rate": -0.35},
                "Disorienting 1": {"cost": 0.35, "delta_win_rate": 0.075},
                "Escalation 1": {"cost": 0.39, "delta_win_rate": 0.085},
                "Guarantee 1": {"cost": 0.00, "delta_win_rate": 0},
                "Immobilize 1": {"cost": 0.02, "delta_win_rate": 0.005},
                "Magical 1": {"cost": 7.71, "delta_win_rate": 0.49},
                "Penetration 1": {"cost": 0.00, "delta_win_rate": 0},
                "Reload 1": {"cost": -1.43, "delta_win_rate": -0.42},
                "Risk 1": {"cost": -0.37, "delta_win_rate": -0.13},
                "Slow 1": {"cost": 0.02, "delta_win_rate": 0.005},
                "Stabilization 1": {"cost": 0.89, "delta_win_rate": 0.185},
                "Stun 1": {"cost": 0.63, "delta_win_rate": 0.135},
            },
        },
    },
    2: {
        "rank": 2,
        "property_costs": {
            "melee": {
                "Accuracy 1": {"cost": 1.53, "delta_win_rate": 0.19},
                "Armor Pierce 1": {"cost": -0.03, "delta_win_rate": -0.005},
                "Bleed 1": {"cost": 0.00, "delta_win_rate": 0},
                "Dangerous 1": {"cost": -1.09, "delta_win_rate": -0.195},
                "Disorienting 1": {"cost": 0.00, "delta_win_rate": 0},
                "Escalation 1": {"cost": 0.22, "delta_win_rate": 0.03},
                "Guarantee 1": {"cost": 0.00, "delta_win_rate": 0},
                "Immobilize 1": {"cost": 0.00, "delta_win_rate": 0},
                "Magical 1": {"cost": 10.25, "delta_win_rate": 0.495},
                "Penetration 1": {"cost": 0.00, "delta_win_rate": 0},
                "Reach 1": {"cost": 0.00, "delta_win_rate": 0},
                "Risk 1": {"cost": -0.72, "delta_win_rate": -0.13},
                "Slow 1": {"cost": 0.00, "delta_win_rate": 0},
                "Stun 1": {"cost": 0.00, "delta_win_rate": 0},
            },
            "ranged": {
                "Accuracy 1": {"cost": 1.56, "delta_win_rate": 0.19},
                "Aggressive Fire 1": {"cost": 2.62, "delta_win_rate": 0.265},
                "Armor Pierce 1": {"cost": -0.03, "delta_win_rate": -0.005},
                "Bleed 1": {"cost": 0.00, "delta_win_rate": 0},
                "Dangerous 1": {"cost": -1.11, "delta_win_rate": -0.205},
                "Disorienting 1": {"cost": 0.58, "delta_win_rate": 0.08},
                "Escalation 1": {"cost": 0.18, "delta_win_rate": 0.025},
                "Guarantee 1": {"cost": 0.00, "delta_win_rate": 0},
                "Immobilize 1": {"cost": 0.00, "delta_win_rate": 0},
                "Magical 1": {"cost": 10.03, "delta_win_rate": 0.455},
                "Penetration 1": {"cost": -0.03, "delta_win_rate": -0.005},
                "Reload 1": {"cost": -2.36, "delta_win_rate": -0.425},
                "Risk 1": {"cost": -0.57, "delta_win_rate": -0.105},
                "Slow 1": {"cost": 0.04, "delta_win_rate": 0.005},
                "Stabilization 1": {"cost": 0.88, "delta_win_rate": 0.12},
                "Stun 1": {"cost": 0.00, "delta_win_rate": 0},
            },
        },
    },
    3: {
        "rank": 3,
        "property_costs": {
            "melee": {
                "Accuracy 1": {"cost": 2.00, "delta_win_rate": 0.155},
                "Armor Pierce 1": {"cost": 0.05, "delta_win_rate": 0.005},
                "Bleed 1": {"cost": 0.05, "delta_win_rate": 0.005},
                "Dangerous 1": {"cost": -1.25, "delta_win_rate": -0.13},
                "Disorienting 1": {"cost": 0.05, "delta_win_rate": 0.005},
                "Escalation 1": {"cost": 0.21, "delta_win_rate": 0.02},
                "Guarantee 1": {"cost": 0.05, "delta_win_rate": 0.005},
                "Immobilize 1": {"cost": 0.05, "delta_win_rate": 0.005},
                "Magical 1": {"cost": 10.63, "delta_win_rate": 0.49},
                "Penetration 1": {"cost": 0.05, "delta_win_rate": 0.005},
                "Reach 1": {"cost": 0.05, "delta_win_rate": 0.005},
                "Risk 1": {"cost": -1.17, "delta_win_rate": -0.12},
                "Slow 1": {"cost": 0.05, "delta_win_rate": 0.005},
                "Stun 1": {"cost": 0.05, "delta_win_rate": 0.005},
            },
            "ranged": {
                "Accuracy 1": {"cost": 1.91, "delta_win_rate": 0.15},
                "Aggressive Fire 1": {"cost": 4.39, "delta_win_rate": 0.25},
                "Armor Pierce 1": {"cost": 0.00, "delta_win_rate": 0},
                "Bleed 1": {"cost": 0.00, "delta_win_rate": 0},
                "Dangerous 1": {"cost": -1.24, "delta_win_rate": -0.135},
                "Disorienting 1": {"cost": 0.73, "delta_win_rate": 0.07},
                "Escalation 1": {"cost": 0.15, "delta_win_rate": 0.015},
                "Guarantee 1": {"cost": 0.00, "delta_win_rate": 0},
                "Immobilize 1": {"cost": 0.00, "delta_win_rate": 0},
                "Magical 1": {"cost": 10.95, "delta_win_rate": 0.45},
                "Penetration 1": {"cost": 0.05, "delta_win_rate": 0.005},
                "Reload 1": {"cost": -3.38, "delta_win_rate": -0.4},
                "Risk 1": {"cost": -0.95, "delta_win_rate": -0.1},
                "Slow 1": {"cost": 0.10, "delta_win_rate": 0.01},
                "Stabilization 1": {"cost": 0.95, "delta_win_rate": 0.09},
                "Stun 1": {"cost": 0.00, "delta_win_rate": 0},
            },
        },
    },
    4: {
        "rank": 4,
        "property_costs": {
            "melee": {
                "Accuracy 1": {"cost": 1.58, "delta_win_rate": 0.09},
                "Armor Pierce 1": {"cost": 0.00, "delta_win_rate": 0},
                "Bleed 1": {"cost": 0.00, "delta_win_rate": 0},
                "Dangerous 1": {"cost": -2.00, "delta_win_rate": -0.08},
                "Disorienting 1": {"cost": 0.00, "delta_win_rate": 0},
                "Escalation 1": {"cost": 0.18, "delta_win_rate": 0.01},
                "Guarantee 1": {"cost": 0.00, "delta_win_rate": 0},
                "Immobilize 1": {"cost": 0.00, "delta_win_rate": 0},
                "Magical 1": {"cost": 8.00, "delta_win_rate": 0.405},
                "Penetration 1": {"cost": 0.00, "delta_win_rate": 0},
                "Reach 1": {"cost": 0.00, "delta_win_rate": 0},
                "Risk 1": {"cost": -2.10, "delta_win_rate": -0.085},
                "Slow 1": {"cost": 0.00, "delta_win_rate": 0},
                "Stun 1": {"cost": 0.00, "delta_win_rate": 0},
            },
            "ranged": {
                "Accuracy 1": {"cost": 1.68, "delta_win_rate": 0.1},
                "Aggressive Fire 1": {"cost": 4.50, "delta_win_rate": 0.21},
                "Armor Pierce 1": {"cost": 0.00, "delta_win_rate": 0},
                "Bleed 1": {"cost": 0.00, "delta_win_rate": 0},
                "Dangerous 1": {"cost": -2.20, "delta_win_rate": -0.095},
                "Disorienting 1": {"cost": 1.07, "delta_win_rate": 0.06},
                "Escalation 1": {"cost": 0.18, "delta_win_rate": 0.01},
                "Guarantee 1": {"cost": 0.00, "delta_win_rate": 0},
                "Immobilize 1": {"cost": 0.00, "delta_win_rate": 0},
                "Magical 1": {"cost": 9.00, "delta_win_rate": 0.425},
                "Penetration 1": {"cost": 0.09, "delta_win_rate": 0.005},
                "Reload 1": {"cost": -6.18, "delta_win_rate": -0.365},
                "Risk 1": {"cost": -1.67, "delta_win_rate": -0.07},
                "Slow 1": {"cost": 0.27, "delta_win_rate": 0.015},
                "Stabilization 1": {"cost": 1.07, "delta_win_rate": 0.06},
                "Stun 1": {"cost": 0.00, "delta_win_rate": 0},
            },
        },
    },
}
